### ISSUE TITLE
Macbook Pro 2020 & go version 1.19.2

### ISSUE THREAD

**Issue by Teicu** [praetorian-inc/fingerprintx#11]
Hi, 

Doesn't seem to work in Mac. 

No matter what command I use it doesn't give me any results 

I tried by example:  

> ./fingerprintx -t acunetix.com:443  
> cat target.txt | ./fingerprintx 
> ./fingerprintx -l target.txt  

It gives me absolutely no errors at all, no results, nothing. 

I tried the latest version released, of course. 

Cheers

**Comment by Teicu** [comment]
by the way, I think it should also work with subfinder or findomain, or am I wrong? 

I mean something like : 

> findomain -t google.com |  fingerprintx

**Comment by praetorian-thendrickson** [comment]
to use it in a chain with subfinder, you can do:
```
subfinder -silent -d google.com | naabu -silent | fingerprintx
```

**Comment by Teicu** [comment]
Hi 

Thank you very much, now it works perfectly!

_./fingerprintx -t acunetix.com:443
https://acunetix.com:443 (52.54.58.130)_ 

Kind regards
