### ISSUE TITLE
Incorrect return of linux RPC protocol name

### ISSUE THREAD

**Issue by poq79** [praetorian-inc/fingerprintx#25]
It was supposed to show RPC protocol, but it showed RDP protocol.
There is a mistake on line 310 in the pkg/plugins/types.go file
`
func (e ServiceRPC) Type() string { return ProtoRDP }
`

**Comment by praetorian-thendrickson** [comment]
Thanks for the PR! Just merged the fix

**Comment by praetorian-thendrickson** [comment]
Just released v1.1.11 with your fix, thanks for the pr!
